### ISSUE TITLE
build fails on windows

### ISSUE THREAD

**Issue by parthibx24** [Tencent/tquic#41]
When building in a windows environment I encountered the following issues.

### 1. boringssl cant find ssl and crypto libraries
```sh
   Compiling tquic v0.2.0 (E:\Docs\devw\2023\tquic)
error: could not find native static library `ssl`, perhaps an -L flag is missing?

error: could not compile `tquic` (lib) due to previous error
```
Looks like the libraries are stored under the `out/build/Debug` folder not `out/build`. Can be fixed by adding this folder in build.rs.
```sh
    Directory: E:\Docs\devw\2023\tquic\target\debug\build\tquic-959af7c8517dba55\out\build\Debug


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        11/20/2023  10:31 PM        5014178 crypto.lib
-a----        11/20/2023  10:33 PM        1619950 ssl.lib
```

### 2. jemalloc wont compile
```sh
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
The following warnings were emitted during compilation:


error: failed to run custom build command for `tikv-jemalloc-sys v0.5.4+5.3.0-patched`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `E:\Docs\devw\2023\tquic\target\debug\build\tikv-jemalloc-sys-eafeea802f535c08\build-script-build` (exit code: 101)
  --- stdout
  TARGET=x86_64-pc-windows-msvc
  HOST=x86_64-pc-windows-msvc
  NUM_JOBS=12
  OUT_DIR="E:\\Docs\\devw\\2023\\tquic\\target\\debug\\build\\tikv-jemalloc-sys-abde19670416cf39\\out"
  BUILD_DIR="E:\\Docs\\devw\\2023\\tquic\\target\\debug\\build\\tikv-jemalloc-sys-abde19670416cf39\\out\\build"
  SRC_DIR="C:\\Users\\ant\\scoop\\persist\\rustup-msvc\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tikv-jemalloc-sys-0.5.4+5.3.0-patched"
  cargo:warning="jemalloc support for `x86_64-pc-windows-msvc` is untested"
  cargo:rustc-cfg=prefixed
  cargo:rerun-if-env-changed=JEMALLOC_OVERRIDE
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  CC="C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\cl.exe"
  CFLAGS="-nologo -MD -Z7 -Brepro -W4"
  JEMALLOC_REPO_DIR="jemalloc"
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_MALLOC_CONF
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_PAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_HUGEPAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_QUANTUM
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_VADDR
  --with-jemalloc-prefix=_rjem_
  running: "sh" "E:/Docs/devw/2023/tquic/target/debug/build/tikv-jemalloc-sys-abde19670416cf39/out/build/configure" "--disable-cxx" "--enable-doc=no" "--enable-shared=no" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-pc-win32" "--build=x86_64-pc-win32" "--prefix=E:\\Docs\\devw\\2023\\tquic\\target\\debug\\build\\tikv-jemalloc-sys-abde19670416cf39\\out"
  checking for xsltproc... false
  checking for x86_64-pc-win32-gcc... C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\cl.exe
  checking whether the C compiler works... no
  running: "tail" "-n" "100" "E:\\Docs\\devw\\2023\\tquic\\target\\debug\\build\\tikv-jemalloc-sys-abde19670416cf39\\out\\build\\config.log"

  --- stderr
  configure: error: in `/e/Docs/devw/2023/tquic/target/debug/build/tikv-jemalloc-sys-abde19670416cf39/out/build':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
  thread 'main' panicked at C:\Users\ant\scoop\persist\rustup-msvc\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tikv-jemalloc-sys-0.5.4+5.3.0-patched\build.rs:347:19:
  failed to execute command: program not found
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
     1: core::panicking::panic_fmt
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
     2: build_script_build::main::{{closure}}
     3: build_script_build::main::{{closure}}
     4: build_script_build::main::{{closure}}
     5: build_script_build::main::{{closure}}
     6: build_script_build::main::{{closure}}
     7: <core::str::pattern::CharSearcher as core::str::pattern::Searcher>::haystack
     8: core::fmt::Arguments::new_const
     9: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
    10: std::rt::lang_start
    11: std::rt::lang_start_internal::closure$2
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
    12: std::panicking::try::do_call
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:502
    13: std::panicking::try
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:466
    14: std::panic::catch_unwind
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panic.rs:142
    15: std::rt::lang_start_internal
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
    16: std::rt::lang_start
    17: main
    18: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    19: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    20: BaseThreadInitThunk
    21: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
as a workaround this library can be disabled for windows

**Comment by iyangsj** [comment]
@parthibx24 Thank you for your detailed feedback and suggestions!

As outlined in the [project documentation](https://tquic.net/docs/getting_started/installation/#supported-platforms) , TQUIC does not currently support Windows OS.

However, We plan to extend its support to Windows in later versions.
